// layout.js
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./Components/Sidebar";
import Topbar from "./Components/Topbar";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import "../lib/fontawesome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BIBLIOFRID",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex h-screen">
          {/* Sidebar fijo */}
          <div className="w-[120px] bg-gray-800 text-white">
            <Sidebar />
          </div>

          {/* Área derecha: Topbar + Contenido */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Topbar sticky */}
            <div className="sticky top-0 z-10 bg-gray-800">
              <Topbar />
            </div>

            {/* Contenido scrollable */}
            <AuthProvider>
              <main className="flex-1 overflow-y-auto bg-gray-100 p-6">
                {children}
              </main>
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
